export { default as HeroBlock } from './HeroBlock/HeroBlock.jsx';
export { default as Discounts } from './Discounts/Discounts.jsx';
export { default as About } from './About/About.jsx';
export { default as Testimonials } from './Testimonials/Testimonials.jsx';
export { default as EcoFriendly } from './EcoFriendly/EcoFriendly.jsx';
export { default as Positions } from './Positions/Positions.jsx';
export { default as News } from './News/News.jsx';
export { default as OurProducts } from './OurProducts/OurProducts.jsx';
export { default as WeOffer } from './WeOffer/WeOffer.jsx';